cloudquery/.github

- workflows/providers/release.yml
- workflows/providers/test_integration.yml
- workflows/providers/test_unit.yml
- workflows/repo-specific/cloudquery/history_test.yml
- workflows/repo-specific/cloudquery/release.yml
- workflows/repo-specific/cloudquery/test.yml
Prior implementation was super verbose and not clean
> chore: Cleaner implementation

- workflows/repo-specific/cq-provider-aws/endpoints.yml
Fixes https://github.com/cloudquery/cq-provider-aws/issues/652
> chore: Automate endpoints generation

- workflows/common/pr_title.yml
Fixes https://github.com/cloudquery/cloudquery-issues/issues/316 (internal issue), specifically https://github.com/cloudquery/cloudquery-issues/issues/316#issuecomment-1100873293
> chore(ci): don't validate single commits

- .github/workflows/sync_files.yml
Fixes https://github.com/cloudquery/.github/issues/21
See v2 changes in https://github.com/BetaHuhn/repo-file-sync-action/pull/201
> feat: use templating brach v2

- .github/workflows/sync_files.yml
🤦  Forgot to enable the templating feature
> fix(sync): enable templating

- misc/Makefile
Bringing https://github.com/cloudquery/cq-provider-aws/pull/794 into this repo
> chore(makefile): Better db migration prefix suggestion

- .github/sync.yml
- misc/PULL_REQUEST_TEMPLATE.md
- misc/PULL_REQUEST_TEMPLATE_terraform.md
Adds a pull request template for providers
> feat: Add providers pull request template

- workflows/common/lint_golang.yml
- workflows/providers/lint_doc.yml
- workflows/providers/test_integration.yml
- workflows/providers/test_integration.yml.cq-provider-aws.values.yml
- workflows/providers/test_integration.yml.cq-provider-azure.values.yml
- workflows/providers/test_integration.yml.cq-provider-gcp.values.yml
- workflows/providers/test_unit.yml
- workflows/terraform/terraform_apply.yml
- workflows/terraform/terraform_plan.yml
- workflows/terraform/terraform_plan.yml.cq-provider-aws.values.yml
- workflows/terraform/terraform_plan.yml.cq-provider-gcp.values.yml
This ensures status checks are set on PRs, even when paths are ignored
> chore(ci): Replace paths-ignore with paths-filter

- .github/workflows/sync_files.yml
> feat: Assign sync PRs

- .github/workflows/sync_files.yml
Fixes https://github.com/cloudquery/.github/pull/44
> fix: Fix assignee

- workflows/common/lint_golang.yml
- workflows/providers/lint_doc.yml
- workflows/providers/test_unit.yml
> fix: Check for correct event type

- workflows/repo-specific/cloudquery/sanity.yml
Bring the changes from https://github.com/cloudquery/cloudquery/pull/623
> fix: Update cloudquery workflows

- workflows/providers/test_integration.yml.cq-provider-terraform.values.yml
> feat: Add terraform provider

- misc/Makefile
Brings https://github.com/cloudquery/cq-provider-aws/pull/848/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L49 into this repo
> fix(providers): Fix makefile fetch target

- misc/providers/.goreleaser.yaml
Not required for release process
> fix: Remove go generate from release flow

- misc/issue_reporting.md.cq-provider-terraform.values.yml
Replaced by https://github.com/cloudquery/.github/pull/69
> fix: Delete redundant file

- workflows/policies/release-pr.yml
- workflows/providers/release-pr.yml
- workflows/repo-specific/cloudquery/release-pr.yml
- workflows/repo-specific/cq-provider-sdk/release-pr.yml
> chore: Fix release PR title

- misc/providers/PULL_REQUEST_TEMPLATE.md
- misc/providers/PULL_REQUEST_TEMPLATE_terraform.md
- fixed link to `contributing.md` which was not working during pr creation.
> fix: Fixed link to contributing.md in pr templates

- workflows/providers/release-pr.yml
- workflows/repo-specific/cloudquery/release-pr.yml
Mark all releases are pre-releases until we finish building and uploading assets
> fix: Mark releases as pre-release until assets are uploaded

- workflows/providers/validate_release.yml
- workflows/repo-specific/cloudquery/validate_release.yml
> fix: Validate release file

- .github/sync.yml
- .github/workflows/sync_repo_settings.yml
- repo-settings/cloudquery/config.yaml
- repo-settings/cq-provider-sdk/config.yaml
- repo-settings/others/config.yaml
- repo-settings/policies/config.yaml
- repo-settings/providers-with-terraform/config.yaml
- repo-settings/providers/config.yaml
- repo-settings/providers/k8s/config.yaml
- repo-settings/providers/with-terraform-and-policy-tests/config.yaml
Draft PR to sync repo settings across our repos.
~~Currently will fail since we need to add the `GH_REPO_SYNC_SETTINGS_TOKEN` token~~
> feat: Sync repo settings

- .github/.kodiak.toml
- .github/sync.yml
So we can auto merge PRs and not wait for CI to complete
> feat: Add kodiak

- .github/workflows/sync_repo_settings.yml
- repo-settings/providers/digitalocean/config.yaml
- workflows/providers/test_integration.yml.cq-provider-digitalocean.values.yml
Fixes https://github.com/cloudquery/cq-provider-digitalocean/issues/77
> fix: Exclude digitalocean integration tests

- workflows/providers/release-pr.yml.cq-provider-template.values.yml
- workflows/providers/test_integration.yml
- workflows/providers/test_integration.yml.cq-provider-aws.values.yml
- workflows/providers/test_integration.yml.cq-provider-azure.values.yml
- workflows/providers/test_integration.yml.cq-provider-gcp.values.yml
- workflows/providers/test_integration.yml.cq-provider-okta.values.yml
- workflows/providers/test_integration.yml.cq-provider-template.values.yml
- workflows/providers/test_integration.yml.cq-provider-terraform.values.yml
Fixes https://github.com/cloudquery/cq-provider-template/issues/69
> fix(template): Don't sync release PR flow, remove slack notification step

- .github/self-hosted-renovate.json5
- .github/workflows/renovate.yml
Fixes https://github.com/cloudquery/.github/issues/118
> feat(renovate): Use GitHub action

- .github/self-hosted-renovate.json5
Follow up on https://github.com/cloudquery/.github/pull/139
> fix: Renovate config

- repo-settings/cloudquery/config.yaml
- repo-settings/cq-provider-sdk/config.yaml
- repo-settings/policies/config.yaml
- repo-settings/providers/config.yaml
- repo-settings/providers/k8s/config.yaml
- repo-settings/providers/no-integration-tests/config.yaml
- repo-settings/providers/with-terraform-and-policy-tests/config.yaml
- workflows/policies/schema_validation.yml
- workflows/providers/test_integration.yml
- workflows/providers/test_policy.yml
- workflows/providers/test_unit.yml
- workflows/repo-specific/cloudquery/policy_test.yml
- workflows/repo-specific/cloudquery/sanity.yml
- workflows/repo-specific/cloudquery/test.yml
Fixes https://github.com/cloudquery/cloudquery/issues/828
> feat: Test only on postgres 10

- .github/sync.yml
- misc/repo-specific/cq-website/CODEOWNERS
Follow up to https://github.com/cloudquery/cq-website/pull/435
> fix: Add cq-website codeowners

- .github/renovate-default.json5
- .github/renovate-node-default.json5
Clean up the config as the default configurations should handle these cases, see https://docs.renovatebot.com/presets-config/#configbase
> fix: Cleanup renovate config

- workflows/policies/schema_validation.yml
- workflows/providers/test_policy.yml
Follow up on https://github.com/cloudquery/cloudquery/releases/tag/v0.28.0
> fix: Update policy tests

- workflows/repo-specific/helm-charts/bump-tf-chart-version.yml
Address feedback from: https://github.com/cloudquery/.github/pull/228
> fix: Address feedback from previous PR

- .github/self-hosted-renovate.json5
Allow docker post upgrade command
> fix: Renovate

- workflows/repo-specific/cloudquery/policy_test.yml
Follow up on https://github.com/cloudquery/cloudquery/pull/1044
> fix: CloudQuery HCL -> YML

- workflows/repo-specific/cloudquery/release.yml
Goes with https://github.com/cloudquery/docs/pull/254
> feat: Sync docs on CLI release

- .github/sync.yml
I missed this in https://github.com/cloudquery/.github/pull/257
> fix: Also sync .pre-commit-config.yaml

- workflows/providers/test_policy_sql.yml
> fix: Test policy sql remove template variable

- workflows/repo-specific/helm-charts/release.yml
> fix: Helm chart releaser

- .github/renovate-default.json5
- .github/renovate-go-default.json5
To reduce noise of dependency updates PRs
> fix(renovate): Schedule updates monthly

- repo-settings/cloudquery/config.yaml
To match https://github.com/cloudquery/cloudquery/pull/1276
> feat: Add release-dry-run protection rule

- .github/.kodiak.toml
Enables auto merge for updates like https://github.com/cloudquery/.github/pull/330
> feat: Auto merge minor updates

- .github/renovate-default.json5
Imports https://github.com/cloudquery/cloudquery/blob/185430104a5cc3086540ea60a3244b72430e0670/.github/renovate.json5#L6
> chore: Update renovate default settings

- .github/renovate-default.json5
- .github/renovate-go-default.json5
- .github/self-hosted-renovate.json5
Several improvements to go version updates PRs (details in comments)
> chore: Improve go version updates

- .github/renovate-node-default.json5
Group nextra packages to a single PR
> feat(deps): Group nextra packages

- .github/renovate-terraform.json5
Replaces:
https://github.com/cloudquery/terraform-aws-cloudquery/blob/b24ee554b6b9c2f2998f3f7800c7aa65d24882c4/.github/renovate.json5
https://github.com/cloudquery/terraform-gcp-cloudquery/blob/45aed7342813a763bc2662b8d618dee30fae7483/.github/renovate.json5
https://github.com/cloudquery/terraform-azure-cloudquery/blob/8cbb3925a8af2d3e08e7f7a6d47cf5863e103c9b/.github/renovate.json5
> feat: Add renovate configuration for terraform repos

- .github/renovate-terraform.json5
Handle updating https://github.com/cloudquery/terraform-gcp-cloudquery/blob/0d88732fb63169009554bf04946962198d1c9059/.github/workflows/pre-commit.yml#L84
> feat: Update terraform docs in GitHub workflows

- .github/renovate-node-default.json5
Going to move this to https://github.com/cloudquery/cloudquery/blob/main/.github/renovate.json5
> chore: Remove Nextra dep group

- .github/renovate-node-default.json5
Same as https://github.com/cloudquery/cloudquery/pull/1844
> chore: Fix renovate config

- .github/.kodiak.toml
Should be handled by https://github.com/cloudquery/.github/pull/350
> chore: Remove redundant Kodiak config

- .github/renovate-go-default.json5
This should make it easier to handle SDK updates in the monorepo
> chore: Add module name to PR title when updating SDK

- .github/renovate-default.json5
These should be regex and not glob patterns
> chore: Fix renovate

- .github/renovate-default.json5
Needed for https://github.com/cloudquery/.github/blob/4af8d3e434462c1d368fed0e85af3d74bdd10756/.github/renovate-terraform.json5#L7
> chore: Include cloudquery/* in instant updates

- .github/renovate-default.json5
CloudQuery monorepo modules should be updated together
> chore(deps): Group monorepo modules updates

- .github/renovate-go-default.json5
Fixes https://github.com/cloudquery/cloudquery/pull/3965#issuecomment-1307776570
> chore(deps): Schedule AWS updates daily

- .github/renovate-default.json5
Related to https://github.com/cloudquery/cloudquery/issues/3971
> chore(deps): Match test plugins in config files

- .github/renovate-default.json5
Not sure this is supported, will test it first
> chore: Make renovate CloudQuery monorepo updates generic

- .github/renovate-default.json5
Should help with https://github.com/cloudquery/helm-charts/pull/243#issuecomment-1386883759
> fix(renovate): Better PR titles

- .github/renovate-go-default.json5
> fix(deps): Don't auto update github.com/cloudquery/arrow

- .github/workflows/sync_arrow.yml
Still need to test this. Related to https://github.com/cloudquery/cloudquery/issues/11168
> feat(ci): Sync `cloudquery/arrow` with `apache/arrow`

- .github/renovate-default.json5
This is useful for our [Monorepo](https://github.com/cloudquery/cloudquery) that has many dependencies
> feat: Update `prConcurrentLimit`

- .github/renovate-default.json5
- .github/workflows/renovate.yml
Should fix https://github.com/cloudquery/cloudquery/issues/1843
> feat: Update renovate

- .github/renovate-go-default.json5
Fixes https://github.com/cloudquery/cloudquery-issues/issues/1013
> chore: Group Azure SDK updates on weekly basis

- .github/renovate-default.json5
- .github/workflows/renovate.yml
Used https://try.jsonata.org/ to test using the data for `https://api.cloudquery.io/plugins/cloudquery/source/aws/versions`
Trying to fix https://github.com/cloudquery/cloudquery-issues/issues/954
> feat: Renovate updates from Hub

- .github/renovate-default.json5
Follow up to https://github.com/cloudquery/.github/pull/438
> fix: Remove version template

- .github/renovate-java-default.json5
Reverts cloudquery/.github#448
This was unrelated see https://github.com/cloudquery/.github/pull/449
> chore: Revert "chore: Revert Java config change"

- .github/workflows/renovate.yml
This bumps renovate to v39 to hopefully fix https://github.com/cloudquery/cloud/issues/1737
> fix: bump renovate to v39

- .github/renovate-python-default.json5
Added package rules for grouping grpcio updates.
> chore: Add package rules for grpcio in Renovate config
