cloudquery/.github

.github/sync.yml, workflows/empty/README
- teams cannot cross orgs (so codeowner for policy org needs its own team and file)
- Sync empty directory initially to ensure all files get deleted and action is deterministic
=> fix: Update sync.yml

misc/issue_reporting.md
Hi 👋 
While going over the [issue reporting doc in cq-provider-aws](https://github.com/erezrokah/cq-provider-aws/blob/main/docs/contributing/issue_reporting.md), I noticed some broken links.
This PR fixes those links.
=> chore(docs-issue-reporting): fix links to bug report and feature request

workflows/repo-specific/cloudquery/history_test.yml
Needs to be updated after https://github.com/cloudquery/cloudquery/commit/4c2b3e7dca1b283824299d7c63299ba4167b2026
to avoid overwritng what exists currently in the cloudquery-core repo.
=> chore: Update history_test workflow

misc/issue_reporting.md
Follow up to https://github.com/cloudquery/.github/pull/20
Looks like we don't sync the issue templates from the `.github` repo to other repos (which makes sense to me) so using relatives paths doesn't work.
For example https://github.com/cloudquery/cq-provider-gcp/pull/193 and https://github.com/cloudquery/cq-provider-azure/pull/231.
The reason https://github.com/cloudquery/cq-provider-aws/pull/707 worked is that repo already has the files duplicated.
After this PR is merged I'll follow up with the removal of https://github.com/cloudquery/cq-provider-azure/blob/main/.github/ISSUE_TEMPLATE/ and https://github.com/cloudquery/cq-provider-aws/tree/main/.github/ISSUE_TEMPLATE
=> chore(docs-issue-reporting): link issue templates to .github repo

workflows/repo-specific/cq-provider-aws/endpoints.yml
Related to https://github.com/cloudquery/cloudquery-issues/issues/314 (internal issue).
See performance boost in https://github.com/cloudquery/cq-provider-aws/pull/742#issuecomment-1104155235.
As a follow up we should verify it improves performance for other actions too and if that's the case, implement the same change.
=> chore(ci): Add modules caching

.github/sync.yml
Fixes https://github.com/cloudquery/.github/runs/6189216680?check_suite_focus=true#step:3:225
We can't really comment a line to ignore a repo, so this PR removes it
=> fix: Remove cq-provider-terraform

.github/sync.yml
Brings https://github.com/cloudquery/cq-provider-k8s/pull/85 into this repo
=> fix(providers): Exclude k8s from integration tests

.github/sync.yml
Follow up on https://github.com/cloudquery/.github/pull/63
=> fix: Exclude k8s test_integration

.github/sync.yml
The `release.yml` file was removed in https://github.com/cloudquery/.github/pull/54
=> fix: Sync file

.github/sync.yml, workflows/policies/issue_to_project.yml
Policies are on a different GitHub org, and require a different project board to triage issues
=> fix: Policies issues triage

.github/sync.yml, misc/repo-specific/cloudquery/.goreleaser.prerelease.yaml, workflows/policies/release-pr.yml, workflows/providers/release-pr.yml, workflows/providers/release.yml, workflows/repo-specific/cloudquery/release-pr.yml, workflows/repo-specific/cloudquery/release.yml, workflows/repo-specific/cq-provider-sdk/release-pr.yml
Adds support for pre-releases.
This will:
1. Tag GitHub releases as pre-releases on matching versions (e.g. `v0.0.1-rc1`)
2. Won't publish cloudquery to homebrew on matching versions  (e.g. `v0.0.1-rc1`)
=> feat: Support pre-releases

.github/sync.yml
This is not required as we changed the GitHub action to ignore templates without a matching values file.
=> fix: Remove redundant exclude

misc/repo-specific/cloudquery/.goreleaser.prerelease.yaml, misc/repo-specific/cloudquery/.goreleaser.yaml
Hardcode the key since it's not a secret and we can't use GitHub secrets directly in a `.goreleaser.yaml` file
=> fix: Set Rudder API key

workflows/providers/validate_release.yml, workflows/repo-specific/cloudquery/validate_release.yml
This PR ensures that we don't break GoReleaser on the `main` branch
=> feat: Validate GoReleaser

.github/sync.yml, workflows/common/issue_to_project.yml
Adds auto triage to `cloudquery-issues` repo, and also doesn't triage renovate bot issues
=> feat: Triage cloudquery issues

.github/sync.yml, misc/common/CONTRIBUTING.md, misc/common/PULL_REQUEST_TEMPLATE.md, misc/providers/PULL_REQUEST_TEMPLATE.md
Contributing guide taken from https://github.com/cloudquery/cloudquery/blob/20ad03aa01b13ff87ec2d22b09c1a65002dcb9cc/.github/CONTRIBUTING.md.
We can add a dedicated SDK one later
=> feat: Add missing PR templates and contributing docs

.github/sync.yml, workflows/common/lint_golang.yml
I'm going to sweep the repos and fix any linting errors, so `only-new-issues: true` won't be needed
=> fix(lint): Remove only-new-issues

workflows/providers/test_integration.yml, workflows/providers/test_integration.yml.cq-provider-aws.values.yml, workflows/providers/test_integration.yml.cq-provider-azure.values.yml, workflows/providers/test_integration.yml.cq-provider-gcp.values.yml, workflows/providers/test_integration.yml.cq-provider-okta.values.yml, workflows/providers/test_integration.yml.cq-provider-template.values.yml, workflows/providers/test_integration.yml.cq-provider-terraform.values.yml, workflows/providers/test_integration.yml.cq-provider-test.values.yml
Removes the integration tests from the template completely as `is_organization_member` doesn't work
=> fix: Remove integration test from template

repo-settings/cloudquery/config.yaml
This enforcement is no longer required due to https://github.com/cloudquery/cloudquery/pull/769
=> fix: Remove history test enforcement

misc/common/.golangci.yml
Most of that code is autogenerated
=> fix(go-lint): Ignore cqproto dir

misc/providers/.golangci.yml
Follow up on https://github.com/cloudquery/.github/pull/132
=> fix: Disable nested-structs rule for providers

misc/common/PULL_REQUEST_TEMPLATE.md, misc/providers/PULL_REQUEST_TEMPLATE.md, misc/providers/PULL_REQUEST_TEMPLATE_terraform.md
All the relevant lint PRs are merged so we can tell contributors to run on all the code instead of only their changes
=> fix: Update lint command in PR template

workflows/providers/release.yml
While attempting to use cq-provider-template to build my own
provider, I found that v3 of this action is not able to import 
signing only gpg keys. 
Upgrading to v5 and updating the argument to the new version 
allows the use of a signing only key
=> ci: update ghaction-import-gpg to v5.0.0

misc/providers/.gitignore
`make run` generates `cq-provider`
`go build` generates `cq-provider-<name>`
=> fix(providers-gitignore): Ignore both `cq-provider` and `cq-provider-<name>`

.github/renovate.json5
This will enable dependencies updates for our linting tool and go versions in GitHub workflows
=> feat: Support golangci-lint and go version updates

workflows/providers/test_integration.yml
We should send the Slack notification only if the tests failed on `main` (via push event)
=> fix: Send Slack notification only on push events

workflows/common/pr_title.yml
We can use `chore(ci)` or `fix(docs)`.
For `enhancement`, `feat` should do, and we use `feat!` and `fix!` for breaking changes
=> fix: Semantic commit types

.github/workflows/renovate.yml
Trying to fix https://github.com/cloudquery/.github/runs/7175907724?check_suite_focus=true.
Renovate started failing after the latest upgrade
=> fix: Revert renovate upgrade

misc/common/CONTRIBUTING.md, misc/providers/.pre-commit-config.yaml, misc/providers/Makefile
- Add a pre-commit hook command to the makefile
- Fix a typo in CONTRIBUTING.md
Instructions for the pre-commit itself seems best placed in the `development_environment.md` file, which isn't part of this repo and will need to be managed by each provider separately right now.
=> feat(dev): Add pre-commit hook command to makefile

misc/providers/.pre-commit-config.yaml
This conflicts with the renovate bot that uses --compat=1.17
=> Disable Go Mod Tidy

repo-settings/cloudquery/config.yaml, repo-settings/cq-provider-sdk/config.yaml, repo-settings/providers/config.yaml, repo-settings/providers/k8s/config.yaml, repo-settings/providers/no-integration-tests/config.yaml, repo-settings/providers/with-terraform-tests/config.yaml, workflows/common/lint_golang.yml, workflows/providers/lint_doc.yml, workflows/providers/release.yml, workflows/providers/terraform_apply.yml, workflows/providers/terraform_plan.yml, workflows/providers/test_integration.yml, workflows/providers/test_unit.yml, workflows/providers/validate_release.yml, workflows/repo-specific/cloudquery/release.yml, workflows/repo-specific/cloudquery/sanity.yml, workflows/repo-specific/cloudquery/test.yml, workflows/repo-specific/cloudquery/validate_release.yml, workflows/repo-specific/cq-provider-aws/endpoints.yml, workflows/repo-specific/cq-provider-sdk/unittest.yml
This upgrades the common files to Go 1.18. 
Relates to https://github.com/cloudquery/cloudquery/issues/1147
=> chore: Upgrade to Go 1.18

workflows/providers/check_generated_code_drift.yml, workflows/scripts/regenerate-changed-directories.sh
This adds a workflow to check that generated files do not drift from their definitions. Since this check would fail on many different services right now, it is introduced with a feature flag: only directories containing an .hcl file marked with `//check-for-changes` will be checked. 
Since regeneration is also fairly slow, we only do this on changed resource directories. And if no resource directories changed, the action is completely skipped.
You can see the action being tested on the AWS provider here: https://github.com/cloudquery/cq-provider-aws/pull/1390
=> chore: Add cq-gen drift detection workflow

.github/renovate-go-default.json5, misc/providers/.pre-commit-config.yaml
Brings back https://github.com/cloudquery/.github/pull/265
cc @bbernays and @hermanschaaf.
Now that we've upgraded to Go 1.18 we don't need `gomodTidy1.17` and can use `gomodTidy` as the dependency graph between 1.17 and 1.18 should be the same (not the case for 1.16 and 1.17`).
See more here https://stackoverflow.com/questions/71973152/go-mod-tidy-error-message-but-go-1-16-would-select
=> fix(renovate): Use go mod tidy instead of compat=1.17

repo-settings/cloudquery/config.yaml
This reverts commit 22a8b60a3aa32b8759b8037ca8601f13a60b8f75.
This checks don't run for cloudflare and github, I made a mistake thinking they do
=> Revert "chore: Add SQLPolicyTest required checks (#300)"

.github/renovate-default.json5
Usually updating our linter or go version must be done together, see:
https://github.com/cloudquery/plugin-sdk/pull/37
https://github.com/cloudquery/plugin-sdk/pull/36
This should group these updates to a single PR
=> chore: Group linter and go versions updates

.github/renovate-default.json5, .github/workflows/renovate.yml
The renovate GitHub actions runs renovate in a docker container so we can't install tools like `gofmt`.
We should wait for https://github.com/renovatebot/github-action/issues/625 to use the renovate non slim image that has `gofmt` pre-installed
=> fix(renovate): Don't run gofmt after go updates

.github/.kodiak.toml, .github/renovate-default.json5
Improves dependencies auto merge to support `digest` (common in `go` modules). Kodiak only supports SemVer based updates, so we use renovate logic to add the `automerge` label
=> chore: Improve dependencies automerge

.github/renovate-go-default.json5
This should break the SDK updates into a PR per plugin, so a single failure doesn't block all plugins.
An example is https://github.com/cloudquery/cloudquery/pull/2203 where the only breakage is for destination plugins, but all updates are blocked
=> chore(deps): Split SDK PRs

.github/workflows/renovate.yml
With https://github.com/cloudquery/plugin-sdk/pull/266, running on every hour should be enough
=> chore: Run renovate every hour instead of every 15 minutes

.github/renovate-default.json5
This ignores https://docs.renovatebot.com/presets-default/#ignoremodulesandtests which is a part of the base preset, but results in our test plugins not being updated in the monorepo
=> fix(renovate): Update dependencies for test plugins

.github/renovate-terraform.json5
Auto merging should be based on the version bump type as in https://github.com/cloudquery/.github/blob/6502a3c049cb4591ce3b6adeb962b932081b535c/.github/renovate-default.json5#L36
=> chore: Don't automerge all helm charts updates

.github/renovate-terraform.json5
Ensures we update the examples in the Terraform repos:
https://github.com/cloudquery/terraform-aws-cloudquery/blob/df4ab1e70f14bdff03a3d658a8064d1c4711762f/examples/complete/config.yml
https://github.com/cloudquery/terraform-gcp-cloudquery/blob/16d872fd0d9015bf78610af6b46b7e28233a7bc4/examples/complete/config.yml
https://github.com/cloudquery/terraform-azure-cloudquery/blob/57f98110e139777db47bd5d84c761f2b323ae2f7/examples/complete/config.yml
=> chore(deps): Auto update examples in terraform repositories

.github/renovate-default.json5, .github/renovate-go-default.json5, .github/renovate-terraform.json5
We reference plugins version in many repos:
https://github.com/cloudquery/helm-charts/blob/4a4c8ae89d66714f5d57ef77b9f573847587b0d2/charts/cloudquery/values.yaml#L71
https://github.com/cloudquery/setup-cloudquery/blob/af927fe428033bf187208b036e6c2c9dbcede6cb/example_configs/aws.yml#L4
https://github.com/cloudquery/terraform-aws-cloudquery/blob/6b71f2dd365ea76ce862392f44be389518b01bae/examples/complete/config.yml#L5
And more.
This PR ensures we update the plugins version in all relevant `yml` files
=> chore(deps): Update plugin versions in configs in all repos

.github/renovate-default.json5
This is need due to the way `regex` matchers work:
https://github.com/cloudquery/.github/blob/cee4f3b57cd34306f9e9d9d5e8603cacca3f806b/.github/renovate-default.json5#L56
=> chore: Schedule CloudQuery updates for Helm-Charts at any time

.github/renovate-default.json5
This should allow all SDK updates to be opened at the same time (we have more than 10 plugins) which is the current limit of PRs in `config:base`
=> chore(deps): Set `prConcurrentLimit` to 20

.github/renovate-default.json5
This should fix support for updating our linter
=> fix(deps): Match golangci-lint in all GitHub Actions

.github/renovate-default.json5
This is needed due to https://github.com/cloudquery/.github/pull/381 where I changed the naming convention of the monorepo packages
=> fix(deps): CloudQuery renovate schedule

.github/renovate-default.json5
We don't need this anymore (we only did this since a specific version of the linter required a specific version of Go)
=> chore: Don't group Go and Linter updates

.github/renovate-go-default.json5
See https://docs.renovatebot.com/modules/versioning/#go-modules-directive-versioning
The default is not to bump Go version
=> feat(deps): Update go version in go.mod files

.github/ISSUE_TEMPLATE/config.yml
Make it a bit more clear that people should mostly open issues on the main repo
=> fix: Cleanup issues `config.yml`

.github/renovate-go-default.json5
This should ensure the AWS dependencies PRs use the CI resources when no one is around
=> fix: Update AWS dependencies schedule

.github/renovate-go-default.json5
These updates are a bit noisy at the moment as they happen on each new commit to the Arrow repository
=> fix: Update arrow only once per week

.github/renovate-default.json5, .github/renovate-go-default.json5
Moving this to the default configuration to avoid any ordering issues if someone imports both the `node` preset and the `go` preset. Our monorepo does it and the `node` preset overrides the `go` one
=> fix(deps): Fix arrow schedule

.github/renovate-go-default.json5
Follow up to https://github.com/cloudquery/.github/pull/410.
This ensures we group AWS module updates into a single PR **per plugin** in the monorepo, instead of a single PR for all plugins
More in https://docs.renovatebot.com/configuration-options/#additionalbranchprefix
=> fix: Group AWS updates per plugin

.github/labels.yml, .github/workflows/sync-labels.yml
As our project grows we need more labels and better convention across all our repos.
I mostly took the convention from [k8s labels](https://github.com/kubernetes/kubernetes/labels).
=> chore: Add standard labels

.github/labels.yml
We might also need to add the label to blockers for Kodiaq
=> Add `no automerge` label

.github/renovate-java-default.json5
Not sure why but it seems https://github.com/cloudquery/.github/commit/947d952c75a20343a3c872ba9fd3cbdffd34d77e is causing renovate to run super slow so I'm reverting it
If this doesn't work probably something changed on renovate's side
=> chore: Revert Java config change

.github/workflows/renovate.yml
I think https://github.com/renovatebot/renovate/pull/27621 caused our renovate workflow to run significantly slower (about 2 hours instead of 10 minutes) so trying to use an earlier version
=> chore: Disable renovate request limits

.github/workflows/renovate.yml
Now that https://github.com/renovatebot/renovate/discussions/27759 is fixed we can move to the latest v37 version again
=> chore: Use latest v37 version

.github/renovate-go-default.json5
Should help with https://github.com/cloudquery/cloudquery-issues/issues/2041 until v27 is stable
=> chore: Don't allow docker v27 versions

.github/renovate-node-default.json5
Should help with errors like this
https://github.com/cloudquery/cloudquery/pull/19763
```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: @cloudquery/cq-source-airtable@2.2.10
npm error Found: eslint@8.57.1
npm error node_modules/eslint
npm error   dev eslint@"^8.46.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer eslint@">=9" from eslint-plugin-ava@15.0.1
npm error node_modules/eslint-plugin-ava
npm error   dev eslint-plugin-ava@"^15.0.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error …
```
=> chore: Group eslint updates

.github/renovate-default.json5
This rule groups CLI and plugins update together which is not always desired.
Plugins are still grouped via https://github.com/cloudquery/.github/blob/6f4719b95313b4949ea3a6a00a00d2850cf079a6/.github/renovate-default.json5#L155
=> chore: Remove CLI and plugins update grouping

.github/renovate-default.json5
Example of PR that should be a `chore:`
=> chore: Fix PR title for major GitHub Actions updates
